import "./globals.css";
import { Be_Vietnam_Pro } from "next/font/google";

import Theme from "./_context/styleColor";
import Body from "./body";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-be-vietnam-pro",
});

export const metadata = {
  title: "Universidad Páramo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={beVietnamPro.className + " vscrollbar"}>
        <Theme>
          <Body>{children}</Body>
        </Theme>
      </body>
    </html>
  );
}
